version: '3.8'
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      target: production
    image: api-gateway:prod
    ports:
      - 4050:4000
    env_file:
      - .env.production
    restart: 'on-failure'
