version: '3.8'

services:
  web-app:
    container_name: admin-prod
    image: admin:prod
    build:
      context: .
      target: runner
    ports:
      - 4010:3001
    command: node server
    restart: always
