version: '3.8'

services:
  web-app:
    container_name: web-prod
    image: web:prod
    build:
      context: .
      target: runner
    ports:
      - '3000:3000'
    command: node server
    restart: always
